package enumm;

public enum Ejercicios {
    Press_Banca,
    Press_Banca_Mancuerna,
    Press_Inclinado,
    Press_Inlcinado_Mancuerna,
    Press_Declinado,
    Peck_deck,
    Apertura_poleas,
    Fondos,
    Jalón_pecho,
    Remo_Sentado,
    Remo_Máquina_Hammer,
    Pull_Over,
    Dominadas,
    Pájaros,
    Remo_T,
    Press_militar,
    Elevaciones_Laterales_Polea,
    Curl_predicador,
    Curl_Martillo,
    Extensión_Tríceps,
    Extensión_Encima_Cabeza,
    Patada_tríceps,
    Rompecráneos,
    Curl_muñeca,
    Hand_grip,
    Curl_reverso,
    Prensa,
    Sentadilla_Smith,
    Hack,
    Abductor_Maquina,
    Extensión_Cuadriceps,
    Femoral_Acostado,
    Femoral_Sentado,
    Peso_Muerto_Smith,
    Patada_Glueteo_Polea,
    Hip_Thrust,
    Sentadilla_búlgara,
    Pantorrilla_maquina

}
